### ISSUE TITLE
Mobile experience issues

### ISSUE THREAD

**Issue by dmalyuta** [bhairavmehta95/JustAskMe#11]
- FontAwesome icons do not load for some reason
- UI is too small (e.g. small icons) for easy use on mobile

<img src="https://cloud.githubusercontent.com/assets/12475811/25307009/3f2ca964-274e-11e7-8b37-f174af8d79a3.png" width="50%" />

**Comment by bhairavmehta95** [comment]
Need to change all CSS values from px -> a screen-relative measurement unit (i.e vh , vw)

**Comment by bhairavmehta95** [comment]
Issue: Viewport units no longer work on chrome. Need to find alternative.
