### ISSUE TITLE
Question editing

### ISSUE THREAD

**Issue by dmalyuta** [bhairavmehta95/JustAskMe#13]
A user should be able to modify/delete the questions they've submitted! Use case:
- The question has only one upvote and the user who submitted the question no longer has that question (assumption: one upvote means nobody else in the room has that question)
- The user made a typo/wants to adjust the wording of their question

Possible issues with this: need to think carefully about the mechanics of this, such that a user's individual actions do not influence others (e.g. someone else in the room has the same question, did not upvote but is waiting for the question be answered when the OP deletes the question because he/she has figured it out). Another tricky issue with this: when question matching is implemented, what if two questions are merged because they match, then the OP of the original question changes it such that the two questions no longer would match?

**Comment by bhairavmehta95** [comment]
Not sure if we want to be able to do this.
 @dmalyuta we can discuss.

**Comment by bhairavmehta95** [comment]
Cannot do this because this would require us tracking user's questions that they can edit.

Means we would have to do it within the cookies, which can be edited; so any question could be edited by anyone.
