### ISSUE TITLE
Upvotes do not live-update

### ISSUE THREAD

**Issue by dmalyuta** [bhairavmehta95/JustAskMe#14]
Would be nice for any changes (e.g. upvote counts, question ordering, etc.) to update live across anyone who has the webpage open. E.g. if person A upvotes question 1, person B should see this immediately. If this upvote moves question 1 upward in the "Top" ranking, person A and person B should both see this.

**Comment by bhairavmehta95** [comment]
Look into reloading screen every few seconds, when inactive (i.e how Google News does it).

**Comment by bhairavmehta95** [comment]
http://jsfiddle.net/ScKbk/

```
// on $(document).ready()
setInterval(1 second){
 if (! hasFocus){ callUpdate(); }
}
```

**Comment by bhairavmehta95** [comment]
Fixed, solution:

Every five seconds, it will check if the page is in focus. If not, it will update. Closing issue.
