### ISSUE TITLE
Homepage search button UX

### ISSUE THREAD

**Issue by dmalyuta** [bhairavmehta95/JustAskMe#15]
Moving the mouse away from the search field on the homepage immediately collapses it. An idea for improving UX: collapse the search menu if mouse is away from search menu for more than 10 seconds **counting after the last time that a character was added/deleted from the search menu**. Or simpler solution: remove the animation altogether....

**Comment by bhairavmehta95** [comment]
Fixed.

Solution: 
-Removed css on:hover descriptors; went with full Jquery.
-If the box has text in it, it will no longer collapse.

Closing, reopen if issue still persists.
