### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by bhairavmehta95** [bhairavmehta95/JustAskMe#19]
Move all of UI to: https://semantic-ui.com/

Unfortunately, current UI does not seem to be easily compatible with mobile.

Cannot use `px` or `vh` (viewport units) for mobile, so it may be easier to switch everything over to semantic.

**Comment by bhairavmehta95** [comment]
Update: Home page integrated with semantic UI

**Comment by bhairavmehta95** [comment]
Semantic UI fully integrated, looks great on desktop; need to make it work better on mobile.

**Comment by dmalyuta** [comment]
Agreed

**Comment by bhairavmehta95** [comment]
Mobile UI all finished; iPhone has a problem with zoom on text area, but that is built into iOS so for now, problem will be ignored.
